raevyxSpawnWeight = 0
raevyxMinGroupSize = 1
raevyxMaxGroupSize = 2
raevyxAdditionalBiomes = []
raevyxExcludedBiomes = []
stegonautSpawnWeight = 0
stegonautMinGroupSize = 1
stegonautMaxGroupSize = 4
stegonautAdditionalBiomes = []
stegonautExcludedBiomes = []
cindervaneSpawnWeight = 0
cindervaneMinGroupSize = 1
cindervaneMaxGroupSize = 3
cindervaneAdditionalBiomes = []
cindervaneExcludedBiomes = []
cindervaneEggBlockWorldgen = false
varasuchusSpawnWeight = 0
varasuchusMinGroupSize = 1
varasuchusMaxGroupSize = 2
varasuchusAdditionalBiomes = []
varasuchusExcludedBiomes = []
varasuchusEggBlockWorldgen = true
ignivorusSpawnWeight = 0
ignivorusMinGroupSize = 1
ignivorusMaxGroupSize = 2
ignivorusAdditionalBiomes = []
ignivorusExcludedBiomes = []
volitansSpawnWeight = 0
volitansMinGroupSize = 1
volitansMaxGroupSize = 1
volitansAdditionalBiomes = []
volitansExcludedBiomes = []
nulljawSpawnWeight = 0
nulljawMinGroupSize = 1
nulljawMaxGroupSize = 2
nulljawAdditionalBiomes = []
nulljawExcludedBiomes = []
dragonGriefingEnabled = true
screenShakeEnabled = true
barrelRollEnabled = true
firstPersonBankingCameraEnabled = false
stegonautBuffsEnabled = true
hungerDecayEnabled = true
happinessDecayEnabled = true
ivyHouseEnabled = true
ivyRestockInterval = 36858
