raevyxSpawningEnabled = true
stegonautSpawningEnabled = true
cindervaneSpawningEnabled = true
ignivorusSpawningEnabled = true
varasuchusSpawningEnabled = true
atroxiiaSpawningEnabled = true
volitansSpawningEnabled = true
nulljawSpawningEnabled = true
moopSpawningEnabled = true
mossbackSpawningEnabled = true
ivySpawningEnabled = true
raevyxCustomSpawningEnabled = true
stegonautCustomSpawningEnabled = true
volitansCustomSpawningEnabled = true
raevyxSpawnWeight = 6
raevyxMinGroupSize = 1
raevyxMaxGroupSize = 2
stegonautSpawnWeight = 7
stegonautMinGroupSize = 1
stegonautMaxGroupSize = 4
cindervaneSpawnWeight = 8
cindervaneMinGroupSize = 1
cindervaneMaxGroupSize = 2
atroxiiaSpawnWeight = 6
atroxiiaMinGroupSize = 1
atroxiiaMaxGroupSize = 1
volitansSpawnWeight = 6
volitansMinGroupSize = 1
volitansMaxGroupSize = 1
nulljawSpawnWeight = 4
nulljawMinGroupSize = 4
nulljawMaxGroupSize = 4
moopSpawnWeight = 4
moopMinGroupSize = 1
moopMaxGroupSize = 1
mossbackSpawnWeight = 10
mossbackMinGroupSize = 1
mossbackMaxGroupSize = 2
